"""initial schema

Revision ID: b3e19320fc5b
Revises: 
Create Date: 2026-08-08 20:21:29.507671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e19320fc5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('auth_provider', sa.Enum('TELEGRAM', 'EMAIL', 'PHONE', name='authprovider'), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('is_service_provider', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('follows',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('follower_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('following_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follower_following')
    )
    op.create_table('pets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('species', sa.String(length=40), nullable=False),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('LOST', 'FOUND', 'ADOPT', 'QUESTION', 'GENERAL', name='posttype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('last_seen_location', sa.String(length=200), nullable=True),
    sa.Column('last_seen_lat', sa.Float(), nullable=True),
    sa.Column('last_seen_lng', sa.Float(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_providers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('service_type', sa.Enum('SITTER', 'BOARDING', 'TRAINER', 'VET', 'GROOMER', name='servicetype'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('price_from', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('post_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_reviews',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_reviews')
    op.drop_table('comments')
    op.drop_table('service_providers')
    op.drop_table('posts')
    op.drop_table('pets')
    op.drop_table('follows')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
